version: '3.1'
services:

  server:
    build: ./MainServer
    container_name: attractionMap
    depends_on:
      - main-db
      - cache
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=attractionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=main-db
      - DB_PORT=5432
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379

  auth:
    build: ./AuthServer
    container_name: auth
    depends_on:
      - auth-db
    ports:
      - "8081:8081"
    environment:
      - DB_NAME=authDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=auth-db
      - DB_PORT=5432

  cache:
      image: "redis"
      ports:
        - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  main-db:
    image: postgres:14-alpine
    container_name: attractionDB
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=attractionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=main-db
      - DB_PORT=5432

  auth-db:
    image: postgres:14-alpine
    container_name: authDB
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=authDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=auth-db
      - DB_PORT=5432
