version: '3.1'
services:
  server:
    build: ./
    container_name: attractionMap
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=attractionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=attractionDB
      - DB_PORT=5432

  db:
    image: postgres:14-alpine
    container_name: attractionDB
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=attractionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=attractionDB
      - DB_PORT=5432
