version: '3.1'
services:
  server:
    build: ./
    container_name: attractionMap
    depends_on:
      - db
      - cache
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=attractionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=attractionDB
      - DB_PORT=5432
      - SPRING_REDIS_HOST=cache
      - SPRING_REDIS_PORT=6379
  cache:
      image: "redis"
      ports:
        - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  db:
    image: postgres:14-alpine
    container_name: attractionDB
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=attractionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=attractionDB
      - DB_PORT=5432
